-- FUNCAO (ManyToMany com Usuario)
CREATE TABLE FUNCAO (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(20 CHAR) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

-- USUARIO
CREATE TABLE T_USUARIOS (
    id_usuario NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100 CHAR) NOT NULL,
    email_usuario VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    senha VARCHAR2(100 CHAR) NOT NULL,
    cadastro DATE,
    cpf VARCHAR2(14 CHAR) NOT NULL UNIQUE,
    PRIMARY KEY (id_usuario)
);

-- Vínculo ManyToMany entre Usuário e Função
CREATE TABLE USUARIO_FUNCAO_TAB (
    id_funcao NUMBER(19) NOT NULL,
    id_usuario NUMBER(19) NOT NULL,
    PRIMARY KEY (id_funcao, id_usuario)
);

-- CURSO (referencia professor, que é um Usuario)
CREATE TABLE T_CURSO (
    id_curso NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nome_curso VARCHAR2(150 CHAR) NOT NULL,
    descricao CLOB,
    qt_horas NUMBER(10),
    id_professor NUMBER(19), -- FK para Usuario (Professor)
    PRIMARY KEY (id_curso)
);

-- CERTIFICADO (referencia Usuario e Curso)
CREATE TABLE T_CERTIFICADO (
    id_certificado NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    dt_emissao DATE,
    descricao VARCHAR2(200 CHAR),
    codigo_validacao VARCHAR2(50 CHAR),
    id_usuario NUMBER(19) NOT NULL,
    id_curso NUMBER(19) NOT NULL,
    PRIMARY KEY (id_certificado)
);
